### PR TITLE
Works on Mac OS X 10.5

### PR DESCRIPTION
**Pull request by arnaudgelas**
FIX: work with gcc > 4.0.0
FIX: compilation error on Mac OS X 10.5

TODO: allow people to report issues / bug report
TODO: VisomicsData address

### CODE REVIEW

**Comment by wturner** [comment]
Thanks Arnaud.  We are still getting this launched completely, but it is
great that you have already contributed! :-)
- Wes

On Thu, Dec 29, 2011 at 6:04 AM, Arnaud Gelas <
reply@reply.github.com

> wrote:
> 
> FIX: work with gcc > 4.0.0
> FIX: compilation error on Mac OS X 10.5
> 
> TODO: allow people to report issues / bug report
> TODO: VisomicsData address
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/arnaudgelas/Visomics master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/brianhelba/Visomics/pull/1
> 
> -- Commit Summary --
> - Add .gitignore
> - Works with gcc 4.0.0 (Mac 10.5)
> - Temporarily commented (wrong address)
> - fix compilation error on Mac 10.5
> 
> -- File Changes --
> 
> A .gitignore (5)
> M Base/Testing/Cpp/voDataObjectTest.cpp (3)
> M CMakeLists.txt (2)
> M SuperBuild.cmake (2)
> 
> -- Patch Links --
> 
>  https://github.com/brianhelba/Visomics/pull/1.patch
>  https://github.com/brianhelba/Visomics/pull/1.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/brianhelba/Visomics/pull/1

## 

Wesley D. Turner, Ph.D.
Kitware, Inc.
Technical Leader
28 Corporate Drive
Clifton Park, NY 12065-8662
Phone: 518-881-4920

**Comment by arnaudgelas** [comment]
Hi Wes,

I have been working in a systems biology lab, so this software could definitively of interest. I am looking forward to giving it a try!

Best,
Arnaud

**Comment by arnaudgelas** [comment]
Would it be possible to enable "issues" on the repository to be able to report bugs, feature request, please?

Thanks!

**Comment by wturner** [comment]
Arnaud,

You are an early adopter and beat the (final version of) the bug tracker!

We are setting up a Mantis installation in the same framework that ITK
uses.  Right now, it is at https://www.kitware.com/Bug/  You should be able
to go there and set up an account.  If you send me the account name, I will
grant you access to the project.  Over the next few days, this will be
migrated out to a more visible location without the requirement to have an
account before reporting issues ... We will migrate all existing issues
from the current one to the new one once it is ready.

BTW: http://visomics.org has some pretty text and pull down links for what
we have set up so far.

Finally,  thanks for your interest.  We are interested in pushing this
forward and that cannot happen in a useful fashion without building a
larger community.  We are excited that you have an interest and look
forward to working with you as we roll this forward.
- Wes

On Thu, Jan 5, 2012 at 2:32 AM, Arnaud Gelas <
reply@reply.github.com

> wrote:
> 
> Would it be possible to enable "issues" on the repository to be able to
> report bugs, feature request, please?
> 
> Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Visomics/Visomics/pull/1#issuecomment-3366575

## 

Wesley D. Turner, Ph.D.
Kitware, Inc.
Technical Leader
28 Corporate Drive
Clifton Park, NY 12065-8662
Phone: 518-881-4920
